### PR TITLE
:sparkles: Dashboard page + Create & Join room

### PR DESCRIPTION
**Pull request by ZerLock**
@ZiplEix Can you make the frontend part, adding your awesome logo. The two backend endpoint `/api/room/create` & `/api/room/join` are ready ! You can see on firestore a game just created after this PR and tell me if I forgot some things :)

:warning: Please do not accept this PR until the frontend is not finished

### CODE REVIEW

**Comment by ZerLock** [comment]
You can modify all files for the front part. Please if you want to change the backend code, notify me!

**Comment by ZiplEix** [comment]
okay. do you want me to make changes on the same branch? or I make a branch base on your branch?

**Comment by ZiplEix** [comment]
I'll start that tomorrow. I'll be on TT

**Comment by ZiplEix** [comment]
For the moment I don't see anything missing on the game firestore item

**Comment by ZerLock** [comment]
You can modify the front on this branch I will do not modify it now

**Review by ZiplEix — APPROVED** [review]

**Comment by ZerLock** [comment]
Juuuure ça existe encore

**Comment by ZiplEix** [comment]
oui MDR. Je viens de voir ca et ca m'a fait rire

**Pull request merged**
